# Generated by Django 6.0.4 on 2026-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
