# Generated by Django 6.0.4 on 2026-04-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_servicerequest_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_signed', models.BooleanField(default=False)),
                ('provider_signed', models.BooleanField(default=False)),
                ('client_signature', models.CharField(blank=True, max_length=200)),
                ('provider_signature', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='requests.offer')),
            ],
        ),
    ]
